### ISSUE TITLE
Add pre-check on PO file (or better error reporting)

### ISSUE THREAD

**Issue by joelnitta** [joelnitta/dovetail#5]
`md2po` fails if PO file is not correctly formatted, but the error coming from R may not be clear.

For example, in the case of unescaped double quotes.

Trying to run `translate_md()` resulted in an error message like this:

```
> translate_md(
+   md_in = "index.qmd",
+   po = "po/en/index.po",
+   md_out = "locale/en/index.qm")
Translating index.qmd
Error: Traceback (most recent call last):
  File "/usr/local/bin/po2md", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po2md/__main__.py", line 139, in main
    sys.exit(run(args=sys.argv[1:])[1])  # pragma: no cover
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/context.py", line 13, in environ
    yield
    ^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po2md/__main__.py", line 111, in run
    po2md = Po2Md(
            ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po2md/__init__.py", line 120, in __init__
    self.pofiles = paths_or_globs_to_unique_pofiles(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po.py", line 163, in paths_or_globs
```

It was not obvious to me what the problem was.

Further debugging by going inside the docker container and trying to run `po2md` resulted in a more informative error (see last line below):

```
root@638e613aba76:/# po2md 4dc09998642de521ada7adea288bfb5a_1/index.qmd -p 4dc09998642de521ada7adea288bfb5a_2/index.po 
Traceback (most recent call last):
  File "/usr/local/bin/po2md", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po2md/__main__.py", line 139, in main
    sys.exit(run(args=sys.argv[1:])[1])  # pragma: no cover
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/context.py", line 13, in environ
    yield
    ^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po2md/__main__.py", line 111, in run
    po2md = Po2Md(
            ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po2md/__init__.py", line 120, in __init__
    self.pofiles = paths_or_globs_to_unique_pofiles(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mdpo/po.py", line 163, in paths_or_globs_to_unique_pofiles
    polib.pofile(po_filepath, encoding=po_encoding),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polib.py", line 130, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polib.py", line 78, in _pofile_or_mofile
    instance = parser.parse()
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polib.py", line 1348, in parse
    raise IOError('Syntax error in po file %s(line %s): '
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: Syntax error in po file 4dc09998642de521ada7adea288bfb5a_2/index.po (line 27): unescaped double quote found
```

I then fixed the unescaped double quote in one of the `msgtr`s (`lessons indicated in "Lessons Currently in Translation" below` to `lessons indicated in \"Lessons Currently in Translation\" below`) and it fixed the problem.

It would be better if {dovetail} gave some indication of this before attempting translation **OR** surfaced the appropriate error message.

**Comment by joelnitta** [comment]
No longer relevant as we are not using mdpo
